spring:
  application:
    name: ad-filters-subscriber
  profiles:
    active: prod  #切换至 dev 即可输出调试信息

logging:
  file:
    path: ./logs

application:
  config:
    expected_quantity: 2000000  #预期规则数量
    fault_tolerance: 0.001 #容错率
    warn_limit: 6 #警告阈值, 原始规则长度小于该值时会输出警告日志

    # 域名检测，启用时将进行解析以验证域名有效性
    # 注意: 开启此功能可能导致处理时间大幅延长
    domain-detect:
      enable: false
      timeout: 5

  # 规则源配置，remote为远程规则，local为本地规则，支持多个规则源
  rule:
    #远程订阅规则 （！使用前请删除下方示例配置, 注意缩进）
    remote:

      - name: 大圣净化
        path: https://raw.githubusercontent.com/jdlingyu/ad-wars/master/hosts
        type: hosts

      - name: AWAvenue-Adblock-Rule
        path: https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main/AWAvenue-Ads-Rule.txt
        type: easylist
  
      - name: AdGuard_blackmatrix7
        path: https://github.com/blackmatrix7/ios_rule_script/raw/refs/heads/master/rule/AdGuard/AdvertisingTest/AdvertisingTest.txt
        type: easylist

      - name: hagezi/dns-blocklists ultimate
        path: https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/ultimate.txt
        type: easylist

      - name: AdGuard 中文
        path: https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_224_Chinese/filter.txt
        type: easylist
        
      - name: yhosts
        path: https://github.com/VeleSila/yhosts/blob/master/hosts.txt
        type: hosts
        
      - name: 乘风-视频.txt
        path: https://raw.githubusercontent.com/xinggsf/Adblock-Plus-Rule/master/mv.txt
        type: easylist
        
      - name: ADgk_banbendalao.txt
        path: https://raw.githubusercontent.com/banbendalao/ADgk/master/ADgk.txt
        type: easylist
        
      - name: 几十KB的轻量规则.txt
        path: https://raw.githubusercontent.com/damengzhu/banad/main/jiekouAD.txt
        type: easylist
        
      - name: OISD Blocklist Small
        path: https://small.oisd.nl
        type: easylist
        
      - name: HUAWEI
        path: https://raw.githubusercontent.com/hagezi/dns-blocklists/main/domains/native.huawei.txt
        type: easylist

      - name: 小米
        path: https://raw.githubusercontent.com/hagezi/dns-blocklists/main/domains/native.xiaomi.txt
        type: easylist

      - name: 抖音
        path: https://raw.githubusercontent.com/hagezi/dns-blocklists/main/domains/native.tiktok.txt
        type: easylist

      - name: 微软
        path: https://raw.githubusercontent.com/hagezi/dns-blocklists/main/domains/native.winoffice.txt
        type: easylist

      - name: Loyalsoldier/clash-rules 广告域名列表
        path: https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/reject.txt
        type: clash

      - name: Dynamic DNS
        path: https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/dyndns.txt
        type: easylist

      - name: anti-ad smartdns
        path: https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-smartdns.conf
        type: smartdns

      - name: adblock for dnsmasq
        path: https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/adblock-for-dnsmasq.conf
        type: dnsmasq

      - name: anti-ip-attribution
        path: https://raw.githubusercontent.com/SunsetMkt/anti-ip-attribution/main/generated/rule-set-reject.list
        type: clash
        
    #本地规则文件
    #local:
     # - name: 'local rule'
      #  path: 'local-rule.txt' #支持绝对/相对路径

  #输出配置
  output:
    #文件头配置，将自动作为注释添加至每个规则文件开始
    #可使用占位符 ${name}、${type}、${desc} 以及 ${date} (当前日期)
    file_header: |
      ADFS AdBlock ${type}
      Last Modified: ${date}
      Homepage: https://github.com/fhvvbvn/ad-filters-subscriber

    path: rule #输出规则文件的路径，支持绝对/相对路径
    #输出规则文件列表 （！注意缩进，且每个类型只能输出一个文件）
    files:
      - name: easylist.txt     #必要参数: 文件名
        type: easylist         #必要参数: 文件类型: easylist、dnsmasq、clash、smartdns、hosts
        desc: 'ADFS EasyList'  #可选参数: 文件描述，可在file_header中通过 ${} 中使用
        filter:
          - basic              #基本规则，不包含任何控制、匹配符号, 可以转换为 hosts
          - wildcard           #通配规则，仅使用通配符
          - unknown            #其他规则，如使用了正则、高级修饰符号等，这表示目前无法支持

      - name: dns.txt
        type: easylist
        filter:
          - basic
          - wildcard

      - name: dnsmasq.txt
        type: dnsmasq

      - name: clash.yaml
        type: clash

      - name: smartdns.txt
        type: smartdns

      - name: hosts.txt
        type: hosts
